global:
  slack_api_url: 'https://SLACK_WEBHOOK_URL'

route:
  group_by: [alertname, severity]
  receiver: 'blackhole'
  group_wait: 5s
  group_interval: 1m
  repeat_interval: 15m

  routes:
  - match_re:
      severity: 'info|warning|critical'
    receiver: 'slack-prometheus'
    repeat_interval: 8h

receivers:
- name: 'blackhole'
- name: 'slack-prometheus'
  slack_configs:
  - channel: '#prometheus'
    send_resolved: true
    title: '{{ template "slack.my.title" . }}'
    icon_emoji: '{{ template "slack.my.icon_emoji" . }}'
    color: '{{ template "slack.my.color" . }}'
    text: '{{ template "slack.my.text" . }}'
    actions:
    - type: button
      text: 'Query :mag:'
      url: '{{ (index .Alerts 0).GeneratorURL }}'
    - type: button
      text: 'Silence :no_bell:'
      url: '{{ template "__alert_silence_link" . }}'
    - type: button
      text: '{{ template "slack.my.link_button_text" . }}'
      url: '{{ .CommonAnnotations.link_url }}'

templates:
- '/etc/alertmanager/template_slack.yml'
