modules:
  icmp:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip4"
  icmp_v6:
    prober: icmp
    icmp:
      preferred_ip_protocol: "ip6"
  tcp:
    prober: tcp
  http_2xx:
    prober: http
    http:
      preferred_ip_protocol: "ip4"
  http_2xx_v6:
    prober: http
    http:
      preferred_ip_protocol: "ip6"
  ssh_banner:
    prober: tcp
    tcp:
      query_response:
      - expect: "^SSH-2.0-"
      - send: "SSH-2.0-blackbox-ssh-check"
